# Generated by Django 3.0.1 on 2020-02-10 11:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('UploadAndDownload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicantprofile',
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
